# Generated by Django 3.1.1 on 2020-10-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_dotq', '0006_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
